spring:
  rabbitmq:
    password: guest
    listener:
      simple:
        retry:
          max-interval: '30000'
          multiplier: '3.0'
          max-attempts: '10'
          enabled: 'true'
          initial-interval: '5000'
    port: '5672'
    host: localhost
    username: guest
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:~/test1
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jackson:
    serialization:
      fail-on-empty-beans: false
    
      
  application:
    name: Pauta Service 
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
   
service:
  cpf:
    url: https://user-info.herokuapp.com/users/
